### ISSUE TITLE
tabsize = 4 seems forced

### ISSUE THREAD

**Issue by Cottin** [alin23/Cup#1]
Whenever I open a .coffee file after installing your package the tabsize is set to 4 and I have to click and swish it back to to at the bottom of the Sublime window.

My Preferences.sublime-settings - User is set to 2:

```
{
  ...
  "tab_size": 2,
  ...
}
```

When I uninstall your package I get tabsize = 2 again as default.

Thanks for a great package otherwise!!!

**Comment by alin23** [comment]
This happens because of Syntax-specific Settings that Cup sets for `.coffee` and `.litcoffee` files.
You have to modify those settings to make it stick to 2. 
Open a `.coffee` file in Sublime then go to `Sublime Text -> Preferences -> Settings – Syntax Specific` and you can set there
```js
{
    "tab_size": 2
}
```
<img width="469" alt="screenshot 2018-09-29 at 13 26 25" src="https://user-images.githubusercontent.com/3819725/46244706-b3701c80-c3eb-11e8-9c75-5d8200e13fbb.png">

I'm glad you found Cup useful! ^_^ 
Sorry it's littered with all of my personal preferences. The main reason of why I made my own package is that I wanted to stop fiddling with settings whenever I had to use Sublime on a new computer.

**Comment by Cottin** [comment]
Aha, found it, thanks a lot!
Yeah, I like that it adds some more syntax color. It seems like it recognise more things that color schemes can use.
